### PR TITLE
Support for unions

### LINKED ISSUE #70: Add support for parsing unions
Parser should handle [unions](https://doc.rust-lang.org/1.24.0/reference/items/unions.html)

To do this, you'll need this function to parse union contextual keyword:
https://github.com/matklad/libsyntax2/blob/b6f8037a6f8fbcb4f127e1d2b518279650b1f5ea/crates/libsyntax2/src/parser_api.rs#L51-L54

I think it's ok to reuse `STRUCT_DEF` SyntaxKind for unions as well, because they have the same syntax as structs, the difference is in semantics.

struct is handled here: https://github.com/matklad/libsyntax2/blob/b6f8037a6f8fbcb4f127e1d2b518279650b1f5ea/crates/libsyntax2/src/grammar/items/nominal.rs#L3

I think the code should be modified to eat either struct_kw or a union as well. The call site should be updated accordingly

For testing, let's use inline tests. The look like a comment:

https://github.com/matklad/libsyntax2/blob/b6f8037a6f8fbcb4f127e1d2b518279650b1f5ea/crates/libsyntax2/src/grammar/items/nominal.rs#L108-L112

Running `cargo gen-tests` will grep the source for such comments and place the new test cases to `test_data/parser/inline`.

Running `cargo test` then will create the "gold" parse tree as a txt file, which should be examined by hand and committed with a change.

So, we should add such a test comment with `struct` and `union` variants, run `cargo gen-tests`, `cargo test` and that's it?

### PR DESCRIPTION
**Pull request by darksv**
Fixes #70

### CODE REVIEW

**Comment by matklad** [comment]
Travis build indicates that you probably need to re-run `cargo gen-tests`

**Comment by matklad** [comment]
r=me with tests updated
 
@darksv I've added you as a bors review to this repository. Can you check that you can r+ this PR? :)

**Comment by CAD97** [comment]
(Command would be `bors r=matklad` if you want to assign the r correctly, or `bors r+` if you're fine just r'ing it yourself)

**Pull request merged**
