### PR TITLE
Add Clippy to CI

### LINKED ISSUE #19: Setup clippy testing on CI

### PR DESCRIPTION
**Pull request by phansch**
Fixes #19

### CODE REVIEW

**Comment by phansch** [comment]
Let's see how much Clippy is suggesting? Feel free to close the PR if it gets in the way right now :+1:

**Comment by matklad** [comment]
Oh, I am unfortunately in the middle of rewriting significant chunks of the library :(

I’ll get to this PR eventually, but probably not today :-)

**Comment by phansch** [comment]
That's what I saw :) In any case, so far it looks like there are only ~10 suggestions by Clippy.

**Comment by matklad** [comment]
Let's just see how this works out :D

**Pull request merged**
